# Generated by Django 4.2.7 on 2023-11-26 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='green_points',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('1', 'Consapevole Attivista'), ('2', "Guardiano dell'Ambiente"), ('3', 'Ambasciatore Verde'), ('4', 'Pilastro Ecologico'), ('5', 'Spirito della Natura')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
