# Generated by Django 4.2.7 on 2023-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_green_points_customuser_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='green_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
