# Generated by Django 4.2.7 on 2023-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_green_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('saving', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'discount code',
                'verbose_name_plural': 'discount codes',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='accounts.discount'),
        ),
    ]
