# Generated by Django 4.2.7 on 2023-12-02 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_quiz_lives_alter_customuser_green_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quiz_lives',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
