# Generated by Django 4.2.7 on 2023-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_quiz_lives'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('45.4628246;9.0953311', 'Milano'), ('41.902783;12.496365', 'Roma'), ('40.851775;14.268124', 'Napoli'), ('45.070312;7.686857', 'Torino'), ('44.405650;8.946256', 'Genova'), ('44.494887;11.342616', 'Bologna'), ('38.115688;13.361267', 'Palermo')], default='45.4628246;9.0953311', max_length=30),
        ),
    ]
