# Generated by Django 4.2.7 on 2023-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discount_cart_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='cart.discount'),
        ),
    ]
