# Generated by Django 4.2.7 on 2023-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounts',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
