# Generated by Django 4.2.7 on 2023-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'nero'), ('grey', 'grigio'), ('white', 'bianco'), ('blue', 'blu'), ('green', 'verde'), ('yellow', 'giallo'), ('orange', 'arancione'), ('red', 'rosso'), ('purple', 'viola'), ('multicolor', 'multicolore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Uomo'), ('F', 'Donna'), ('U', 'Unisex')], max_length=1),
        ),
    ]
