# Generated by Django 4.2.7 on 2023-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_material_latitude_material_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='average_footprint',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='footprint',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
