# Generated by Django 4.2.7 on 2023-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_average_footprint_alter_product_footprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(default=set, related_name='materials', to='products.material'),
        ),
    ]
