# Generated by Django 4.2.7 on 2023-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='materials', to='products.material'),
        ),
    ]
