# Generated by Django 4.2.7 on 2023-11-29 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
