# Generated by Django 4.2.7 on 2023-11-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
