# Generated by Django 4.2.7 on 2023-12-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_color_size_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
    ]
