# Generated by Django 4.2.7 on 2023-12-03 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
