# Generated by Django 4.2.7 on 2023-12-03 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_location_remove_material_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, editable=False, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
